In [ ]:
from google.colab import drive

In [ ]:
import pandas as pd

In [ ]:
drive.mount("mi_carpeta")

Mounted at mi_carpeta

In [ ]:
%cd mi_carpeta

/content/mi_carpeta

In [ ]:
%ls

Escritorio/  IGNACIO/

In [ ]:
%cd Othercomputers

/content/mi_carpeta/Othercomputers

In [ ]:
%cd "Mi Portátil (1)"

/content/mi_carpeta/Othercomputers/Mi Portátil (1)

In [ ]:
%cd IGNACIO/CODERHOUSE/"Data Science"/"Entregas DataScience"/"Primera PreEntrega"

/content/mi_carpeta/Othercomputers/Mi Portátil (1)/IGNACIO/CODERHOUSE/Data Science/Entregas DataScience/Primera PreEntrega

In [ ]:
%ls

 Coffe.csv                 PrimeraEntrega.ipynb
 Data_AAPL_AMZN_MSFT.csv  'Walmart Data Analysis and Forcasting.csv'

In [ ]:
pd.read_csv("Coffe.csv", sep=",")

,Unnamed: 0,ID,Country of Origin,Lot Number,Company,Number of Bags,Bag Weight,Owner,Variety,Processing Method,...,Aftertaste,Acidity,Body,Balance,Uniformity,Overall,Average points,Moisture Percentage,Color,Expiration
0,0,0,Colombia,CQU2022015,Coffee Quality Union,1,35 kg,Coffee Quality Union,Castillo,Double Anaerobic Washed,...,8.42,8.58,8.25,8.42,10.0,8.58,8.67,11.8,green,"September 21st, 2023"
1,1,1,Taiwan,"The 2022 Pacific Rim Coffee Summit,T037",Taiwan Coffee Laboratory,1,80 kg,Taiwan Coffee Laboratory 台灣咖啡研究室,Gesha,Washed / Wet,...,7.92,8.00,7.92,8.25,10.0,8.50,8.45,10.5,blue-green,"November 15th, 2023"
2,2,2,Laos,"The 2022 Pacific Rim Coffee Summit,LA01",Taiwan Coffee Laboratory,19,25 kg,Taiwan Coffee Laboratory 台灣咖啡研究室,Java,Semi Washed,...,8.08,8.17,7.92,8.17,10.0,8.33,8.43,10.4,yellowish,"November 15th, 2023"
3,3,3,Costa Rica,CQU2022017,Coffee Quality Union,1,22 kg,Coffee Quality Union,Gesha,Washed / Wet,...,8.17,8.25,8.17,8.08,10.0,8.25,8.40,11.8,green,"September 21st, 2023"
4,4,4,Colombia,CQU2023002,Coffee Quality Union,2,24 kg,Coffee Quality Union,Red Bourbon,"Honey,Mossto",...,8.08,8.25,7.92,7.92,10.0,8.25,8.39,11.6,yellow-green,"March 5th, 2024"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,202,Brazil,019/22,Ipanema Coffees,2240,60 kg,Ipanema Coffees,Mundo Novo,Natural / Dry,...,6.92,7.17,7.42,7.17,10.0,7.08,7.51,11.4,green,"February 2nd, 2024"
203,203,203,Nicaragua,017-053-0155,Exportadora Atlantic S.A,300,30 kg,"Exportadora Atlantic, S.A.",SHG,Natural / Dry,...,6.75,7.17,7.42,7.17,10.0,7.08,7.50,10.4,green,"March 2nd, 2024"
204,204,204,Laos,105/3/VL7285-005,Marubeni Corporation,343,60 kg,Ikuto Uehara,Catimor,Washed / Wet,...,7.08,7.00,7.08,7.08,10.0,7.00,7.46,11.6,green,"November 11th, 2023"
205,205,205,El Salvador,0423A01,Aprentium Enterprises LLC,1,2 kg,Roselia Yglesias,Maragogype,Natural / Dry,...,6.75,7.17,7.08,7.00,10.0,6.83,7.26,11.0,bluish-green,"March 7th, 2024"
206,206,206,Brazil,1058 y 1059,Descafeinadores Mexicano SA. de CV,600,60 kg,Descafeinadores Mexicanos S.A de C.V,Mundo Novo,SEMI-LAVADO,...,6.67,6.83,6.83,6.67,10.0,6.67,7.25,11.3,green,"November 18th, 2023"

In [ ]:
coffe_df = pd.read_csv("Coffe.csv", sep=",")

## En esta variable "coffe_df" se guardo el DF con los datos sobre exportaciones de cafe diferentes empresas del mundo. Datos a analizar:
   - Ranking de paises con mas exportaciones
   - Compañias con mas exportaciones 
   - Variedades de Cafe mas significativas
   - Metodos de proceso mas usados
   - máximos, mínimos, promedios, medias y modas de:
        - Acidez
        - Cuerpo
        - Balance 
        - uniformidad
   - Colores mas exportados 
   - Vencimientos mas cortos y mas largos.

In [ ]:
pd.read_csv("Data_AAPL_AMZN_MSFT.csv", delimiter=",")

            date     open     high      low    close     volume  Name
0     08/02/2013  67.7142  68.4014  66.8928  67.8542  158168416  AAPL
1     11/02/2013  68.0714  69.2771  67.6071  68.5614  129029425  AAPL
2     12/02/2013  68.5014  68.9114  66.8205  66.8428  151829363  AAPL
3     13/02/2013  66.7442  67.6628  66.1742  66.7156  118721995  AAPL
4     14/02/2013  66.3599  67.3771  66.2885  66.6556   88809154  AAPL
...          ...      ...      ...      ...      ...        ...   ...
3772  01/02/2018  94.7900  96.0700  93.5813  94.2600   47227882  MSFT
3773  02/02/2018  93.6400  93.9700  91.5000  91.7800   47867753  MSFT
3774  05/02/2018  90.5600  93.2400  88.0000  88.0000   51031465  MSFT
3775  06/02/2018  86.8900  91.4750  85.2500  91.3300   67998564  MSFT
3776  07/02/2018  90.4900  91.7700  89.2000  89.6100   41107592  MSFT

[3777 rows x 7 columns]

In [22]:
stocks_df = pd.read_csv("Data_AAPL_AMZN_MSFT.csv", delimiter=",")

En esta variable "stocks_df" se guardo el DF con los datos sobre las cotizaciones de tres diferentes de las mas grandes empresas IT del mundo. 
En el se analizarán mínimos, máximos, Aperturas y cierres del precio por empresa.
Asi como también, utilizando estos mismos indicadores pero segmentando por espacio temporal (Meses, trimestres, años)

In [ ]:
pd.read_csv("Walmart Data Analysis and Forcasting.csv")

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05/02/2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12/02/2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19/02/2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26/02/2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05/03/2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28/09/2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05/10/2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12/10/2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19/10/2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26/10/2012,760281.43,0,58.85,3.882,192.308899,8.667

In [ ]:
walmart_df = pd.read_csv("Walmart Data Analysis and Forcasting.csv")

En esta variable "walmart_df" se guardo el DF con los datos que se obtuvieron de las distintas sucursales de la empresa walmart con respecto a las ventas de estas. Con indicadores adicionales como ser si eran semanas laborales o de vacaciones, temperatura promedio del dia (para luego analizar si es influyente en el volumen de ventas), el precio del combustible de la ciudad donde pertenece la sucursal, el indice de precios al consumidor de esa ciudad y el indice de desempleo. Todas estas variables adicionales se utilizaran para ver si existe correlación alguna para luego descartar o concretar causalidad. Además de puede hacer un análisis completo por segmentación de cada una de ellas a gusto.